#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OMapScratch.Resource", IsApplication=true)]

namespace OMapScratch
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.1.0.11")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int BackImage = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int DetailLl = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int DetailUr = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExtentFix = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ExtentMove = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int file = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int folder = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int Icon = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int Location = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int Redo = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int RotCompass = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int RotL90 = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int RotNorth = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int Undo = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int ZoomIn = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int ZoomOut = 2130771983;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int btnImages = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int lloTools = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int mniExportImg = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int mniLoad = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int mniLocation = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int mniOrientation = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int mniSave = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int mnuOptions = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int parentLayout = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
